esphome:
  name: solarstation
  platform: ESP32
  board: esp32dev

substitutions:
  updates: 30s

wifi:
  ssid: !secret wifi_sid
  password: !secret wifi_password
  reboot_timeout: 5min

time:
  - platform: sntp
    id: sntp_time
    timezone: "CET-1CEST,M3.5.0,M10.5.0/3"
    servers: "192.168.66.45"

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

mqtt:
  broker: 192.168.66.114

uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 115200
  stop_bits: 1

modbus_controller:
  uart_id: mod_bus
  # ctrl_pin: 5    # if you need to set the driver enable (DE) pin high before transmitting data configure it here
  command_throttle: 0ms
  id: traceranx
  ## the Modbus device addr
  address: 0x1
  ## Any modbus registers not already implemented can be defined here
  ##
  sensors:
    - id: array_rated_voltage
      name: "array_rated_voltage"
      address: 0x3000
      offset: 0
      unit_of_measurement: "V"
      modbus_functioncode: "read_input_registers"
      value_type: U_WORD
      accuracy_decimals: 1
      skip_updates: 60
      filters:
        - multiply: 0.01

  binary_sensors:
    - id: charging_input_volt_failure
      name: "Charging Input Volt Failure"
      modbus_functioncode: read_input_registers
      address: 0x3201
      offset: 0
      bitmask: 0xC000

  text_sensors:
    - name: "rtc_clock"
      id: rtc_clock
      internal: true
      modbus_functioncode: read_holding_registers
      address: 0x9013
      offset: 0
      register_count: 3
      raw_encode: HEXBYTES
      response_size: 6
  #end of modbus_controller

  switches:
    - id: clear_energy_stats
      modbus_functioncode: write_single_coil
      address: 0x14
      offset: 0
      name: "Clear generating  electricity statistic"
      bitmask: 1

  update_interval: 30s

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: traceranx
    name: "rtc clock test 2"
    id: rtc_clock_test2
    internal: true
    modbus_functioncode: read_holding_registers
    address: 0x9013
    offset: 0
    register_count: 3
    raw_encode: HEXBYTES
    response_size: 6

switch:
  - platform: modbus_controller
    modbus_controller_id: traceranx
    id: reset_to_fabric_default
    name: "Reset to Factory Default"
    modbus_functioncode: write_single_coil
    address: 0x15
    bitmask: 1

sensor:
  - platform: modbus_controller
    modbus_controller_id: traceranx
    id: array_rated_current
    name: "array_rated_current"
    address: 0x3000
    offset: 2
    unit_of_measurement: "V"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: traceranx
    id: manual_control_load
    modbus_functioncode: read_coils
    address: 2
    offset: 0
    name: "manual control the load"
    bitmask: 1

